name: Verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven 3.9.9
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.9'

      - name: Build with Maven
        run: mvn -B verify
